
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 3;
const int acc_off_y = -1;
const int acc_off_z = -16;
const float acc_scale_x = 243.423237;
const float acc_scale_y = 256.146824;
const float acc_scale_z = 253.390505;

const int magn_off_x = -17;
const int magn_off_y = -85;
const int magn_off_z = 17;
const float magn_scale_x = 371.022596;
const float magn_scale_y = 358.238415;
const float magn_scale_z = 342.548284;
