
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 1;
const int acc_off_y = 0;
const int acc_off_z = -9;
const float acc_scale_x = 252.920623;
const float acc_scale_y = 259.675014;
const float acc_scale_z = 253.065248;

const int magn_off_x = -26;
const int magn_off_y = -111;
const int magn_off_z = 71;
const float magn_scale_x = 280.628812;
const float magn_scale_y = 292.193556;
const float magn_scale_z = 289.527181;
