
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -4;
const int acc_off_y = 0;
const int acc_off_z = 45;
const float acc_scale_x = 253.538635;
const float acc_scale_y = 265.450254;
const float acc_scale_z = 258.487528;

const int magn_off_x = -22;
const int magn_off_y = -91;
const int magn_off_z = 34;
const float magn_scale_x = 297.940612;
const float magn_scale_y = 292.484339;
const float magn_scale_z = 293.526664;
