
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 0;
const int acc_off_y = 0;
const int acc_off_z = -24;
const float acc_scale_x = 238.812752;
const float acc_scale_y = 255.916640;
const float acc_scale_z = 257.730806;

const int magn_off_x = -31;
const int magn_off_y = -77;
const int magn_off_z = 3;
const float magn_scale_x = 603.665063;
const float magn_scale_y = 577.027289;
const float magn_scale_z = 648.044657;
