
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 6;
const int acc_off_y = 4;
const int acc_off_z = -15;
const float acc_scale_x = 253.742496;
const float acc_scale_y = 260.733193;
const float acc_scale_z = 252.943137;

const int magn_off_x = -31;
const int magn_off_y = -94;
const int magn_off_z = 9;
const float magn_scale_x = 359.786388;
const float magn_scale_y = 351.718291;
const float magn_scale_z = 347.487578;
