
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 4;
const int acc_off_y = -4;
const int acc_off_z = -14;
const float acc_scale_x = 256.020672;
const float acc_scale_y = 257.885241;
const float acc_scale_z = 251.123756;

const int magn_off_x = -32;
const int magn_off_y = -83;
const int magn_off_z = 52;
const float magn_scale_x = 624.478054;
const float magn_scale_y = 608.015417;
const float magn_scale_z = 584.234107;
