
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 4;
const int acc_off_y = 0;
const int acc_off_z = -22;
const float acc_scale_x = 258.184968;
const float acc_scale_y = 258.605101;
const float acc_scale_z = 251.104163;

const int magn_off_x = -56;
const int magn_off_y = -82;
const int magn_off_z = 115;
const float magn_scale_x = 495.429766;
const float magn_scale_y = 585.482060;
const float magn_scale_z = 594.935516;
