
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = 1;
const int acc_off_y = -2;
const int acc_off_z = -8;
const float acc_scale_x = 249.644015;
const float acc_scale_y = 252.926028;
const float acc_scale_z = 249.250033;

const int magn_off_x = -43;
const int magn_off_y = -139;
const int magn_off_z = -15;
const float magn_scale_x = 283.421897;
const float magn_scale_y = 395.838778;
const float magn_scale_z = 303.516302;
