
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -3;
const int acc_off_y = 0;
const int acc_off_z = -19;
const float acc_scale_x = 251.982983;
const float acc_scale_y = 258.755161;
const float acc_scale_z = 252.626119;

const int magn_off_x = -21;
const int magn_off_y = -76;
const int magn_off_z = 70;
const float magn_scale_x = 381.291346;
const float magn_scale_y = 363.729651;
const float magn_scale_z = 357.590952;
